java_library(
    name = "condition",
    srcs = ["Condition.java"],
    visibility = ["//java/aqua:__subpackages__"],
    deps = [
        "//java/aqua/datatypes",
    ],
)

java_library(
    name = "expression",
    srcs = ["Expression.java"],
    visibility = ["//java/aqua:__subpackages__"],
    deps = [
        "//java/aqua/datatypes",
    ],
)
